[features]
seeds = false
[programs.localnet]
evoting_system = "HSmGXbf8A3j7U3Mnf6i9N6tvDCyD5Usp1FSKYHMqDKsz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/khacvy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
